name: Python Build and Push Docker Image

on:
  push:
    branches: [ main ] # Trigger only on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Run CI Tests (Executes your test.sh script)
    - name: Run CI Tests
      run: ./test.sh

    # 3. Set up Docker Buildx (A feature for efficient building)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 4. Login to Docker Hub (Requires Secrets to be configured)
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 5. Build and push the Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/simple-python-app:latest
        # REMINDER: Ensure DOCKER_USERNAME secret is set on GitHub